### ISSUE TITLE
Implement GitHub action for Score

### ISSUE THREAD

**Issue by sujaya-sys** [score-spec/spec#10]
Implement an open-source GitHub action that adds a Score implementation CLI (such as [score-helm](https://github.com/score-spec/score-helm)) to a teams CI toolset. This allows to execute Score automatically and possibly trigger deployments directly from a CI pipeline.

**Comment by Nitishupkr** [comment]
can u give  permission to contribute in this repo

**Comment by sujaya-sys** [comment]
https://github.com/score-spec/setup-score
