### ISSUE TITLE
[BUG] Mail is not working on clicking

### ISSUE THREAD

**Issue by ItsRoy69** [score-spec/spec#46]
### Description

When an user is clicking on the in "https://score.dev/get-started" page, the mailing texts, it doesn't redirects us to mailbox, emailjs  needs to be implemented.

### Expected behavior

When an user is clicking on the in "https://score.dev/get-started" page, the mailing texts, it should redirect us to mailbox

### Steps to reproduce

1. Go to the deployed site
2. Then move to "Get Started" Page -https://score.dev/get-started
3. Click on the Contact us texts
4. It doesn't redirect us

### Screenshots

![Uploading image.png…]()

### Context

I was trying to mail

**Comment by ItsRoy69** [comment]
I'm talking about windows

**Comment by sujaya-sys** [comment]
I'm having issues reproducing this as well. Just to be clear: By "Contact us texts" you're referring to the  "team@score.dev" and "abuse@score.dev" links? Also, which browser are you using? Thanks!
