### ISSUE TITLE
Paid money to get star

### ISSUE THREAD

**Issue by ayushigeorge** [score-spec/spec#54]
### What would you like to share?

Please don't do these tricks suchvas to Pay people for getting more stars on Repo.

**Comment by sujaya-sys** [comment]
Hi @ayushigeorge, we are unaware of any paid programs. This might be related to the issue that was posted by another community member: https://github.com/score-spec/score-helm/issues/18. Please let us know if you come across a similar form and we'll do our best to shut it down. Thank you.
