### ISSUE TITLE
Deprecate resource properties

### ISSUE THREAD

**Issue by sujaya-sys** [score-spec/spec#61]
### Detailed description

* Deprecate resource properties
* Remove from documentation

### Context

[Resource properties](https://docs.score.dev/docs/reference/score-spec-reference/#resource-properties) were added to the Score spec as an option for users to implement validation. Since they aren't utilised by any of the current CLIs and have caused confusion with users did we decide to deprecate them.

### Possible implementation

Mark as deprecated

**Comment by ghen** [comment]
What is the expected behaviour for the CLI tool? Should we look for `properties` and print out the warning into logs (what would be the message), or should we completely ignore those?
CC: @sujaya-sys
