### ISSUE TITLE
Stack error messages in Score implementation CLIs

### ISSUE THREAD

**Issue by sujaya-sys** [score-spec/spec#7]
Currently, if I write a bad flag - the CLI will complain about that, so I’ll fix it. Then I’ll rerun my command and the CLI will complain about the next error message. Is it possible to stack error messages? For example: `Error: unknown flags: --org, --env, --deploy`.

**Comment by enraiha0307** [comment]
Hi, Can I work on this?

**Comment by sujaya-sys** [comment]
@enraiha0307 you're welcome to! This issue exists for both [score-compose](https://github.com/score-spec/score-compose) and [score-helm](https://github.com/score-spec/score-helm) - Please let me know if there's additional engineering input we can provide to support you with solving this task. You can drop in your questions in this thread.

**Comment by enraiha0307** [comment]
@sujaya-sys Thanks, Will let you know.

**Comment by enraiha0307** [comment]
Hello everyone, I was trying to run e2e tests on the main branch but got some failures. I have followed the readme instructions but while running ` go run ./cli` I got this message. 
```bash
❯ go run ./cli
go: no packages loaded from ./cli
```
And after running `robot e2e-tests`
```
------------------------------------------------------------------------------
E2E-Tests.Score-Compose-Examples :: Verification for examples of s... | FAIL |
4 tests, 0 passed, 4 failed
==============================================================================
E2E-Tests                                                             | FAIL |
14 tests, 10 passed, 4 failed
==============================================================================
```
Am I doing something wrong here? Please help.
I have attached the e2e test report zip below.
[report.zip](https://github.com/score-spec/spec/files/10546086/report.zip)

**Comment by sujaya-sys** [comment]
@Nilsty any chance you could take a look at the above described issue? Thanks a lot!

**Comment by Nilsty** [comment]
Hi @enraiha0307 ,
The `go run` command to run score-compose would be `go run ./cmd/score-compose`. I updated it now in the readme. Looking at your test report it seems to be failing as you miss `docker compose` locally. After installing the [compose plugin](https://docs.docker.com/compose/install/linux/) your test should run fine.

**Comment by enraiha0307** [comment]
okay @Nilsty, Thanks for the help. I'll try this.

**Comment by enraiha0307** [comment]
Hi all, I could not contribute much in the past month due to a medical emergency. For this error message, I found that it is being printed and returned by an internal function used inside `Execute()`.
I searched through the cobra package but there was no function or array which would return command line args, Just so that we could parse it ourselves and print the stacked error message.
There was one Property called `DisableFlagParsing: true,` used inside the `Command` struct to disable the parsing and we could write our own small flag parsing function. 
I tried it and was able to print the desired error stack message.
```bash
docker run -it score-compose:latest run -lfjnb
Usage:
  score-compose run [flags]

Flags:
      --build string       Replaces 'image' name with compose 'build' instruction
      --env-file string    Location to store sample .env file
  -f, --file string        Source SCORE file (default "./score.yaml")
  -h, --help               help for run
  -o, --output string      Output file
      --overrides string   Overrides SCORE file (default "./overrides.score.yaml")
      --verbose            Enable diagnostic messages (written to STDERR)

**unknown flags l, j, n, b%**     
  
```
But then after testing for other commands I found that `scoreFileDefault` and `overridesFileDefault` were not getting populated. Therefore using `DisableParsing` will mean writing the whole parsing logic by ourselves.

Another possible solution is to create an issue in `cobra` and add some functionality for returning this stacked error messages or atleast command line args. And then use it in our code. 

So I want your insights/suggestions on this.

**Comment by enraiha0307** [comment]
Hi, I have created a Parser function that iterates through all commands and their respective flags and stores the invalid flags/commands in a slice. It is invoked before `command.Execute()` in `cmd/main.go`. If there are invalid flags/commands, it prints the error stack along with help instructions and ends the program. Only if there are no invalid flags/commands, the `command.Execute()` will run. 
I am working on robot-testcases now.
Let me know if its okay/ needs any other changes.

```
# Sample output:
 ~/ go run ./cmd/score-compose  -levwe
Error: Unknown command/flags: l, e, w, 
Use "score-compose --help" for more information.
```

**Comment by enraiha0307** [comment]
Hi @sujaya-sys, @Nilsty I've run the e2e-tests and got a green report. I've also created a pull request, please review it when you've time. 
https://github.com/score-spec/score-compose/pull/31
[e2e-reports.zip](https://github.com/score-spec/spec/files/11310827/e2e-reports.zip)

**Comment by sujaya-sys** [comment]
Thanks a lot for your contribution @enraiha0307 - I'll make sure we'll get your PR https://github.com/score-spec/score-compose/pull/32 reviewed! 🙂

**Comment by astromechza** [comment]
I'm going to close this and suggest that this is down to individual implementations to implement as they choose.
