### ISSUE TITLE
Slack Invite link is no longer active

### ISSUE THREAD

**Issue by danijam** [score-spec/spec#70]
### What would you like to share?

Trying to join the Score slack. However the join link found both on the score website and the README of this repo just resolve to a page informing you that the invite link is no longer active. Would like to join the score slack!

### Additional information

No

**Comment by sujaya-sys** [comment]
Hi @danijam, thanks for pointing this out! Here's a new invite link that should work for you: https://join.slack.com/t/scorecommunity/shared_invite/zt-2a0x563j7-i1vZOK2Yg2o4TwCM1irIuA. I'll look into updating the outdated link everywhere.
